name: HEAD_YOLOv8n_SCUT_Nano_416_YOLO_RAW_REPRO2
input_model: /workspace/models/HEAD_YOLOv8n_SCUT_Nano_416_YOLO_RAW_REPRO2_yolo_raw.onnx

mean_values: [0, 0, 0]
scale_values: [255, 255, 255]

inputs:
  - name: images
    shape: [1, 3, 416, 416]
    layout: NCHW

outputs:
  - name: cat_13
  - name: cat_14
  - name: cat_15
